# Link repository to Travis CI
# https://travis-ci.org/

# Master branch only
branches:
  only:
  - master

# Set the language
language: python
python:
    - "2.7"

addons:
  apt:
    packages:
      - libopenblas-base
      - libopenblas-dev
      - liblapack-dev
      - gfortran

before_install:
  - pip install --upgrade pip

# command to install dependencies
install:
  - pip install numpy scipy matplotlib pandas sympy nose
  - pip install .

# command to run tests
script: nosetests